import type {
  Employee,
  LeaveRequest,
  Course,
  Notification,
  PayrollRecord,
  AttendanceEntry,
  Document,
  Project,
  JobPosting,
  DashboardStats,
} from "./types"

// Mock Employees Data
export const mockEmployees: Employee[] = [
  {
    id: "1",
    name: "أحمد محمد السعد",
    email: "ahmed.alsaad@company.com",
    phone: "+966501234567",
    position: "مدير الموارد البشرية",
    department: "الموارد البشرية",
    salary: 18000,
    joinDate: "2020-01-15",
    status: "نشط",
    avatar: "/male-avatar.png",
    nationalId: "1234567890",
    birthDate: "1985-03-20",
    address: "الرياض، المملكة العربية السعودية",
    emergencyContact: {
      name: "فاطمة السعد",
      phone: "+966501234568",
      relationship: "زوجة",
    },
    bankAccount: {
      iban: "SA1234567890123456789012",
      bankName: "البنك الأهلي السعودي",
    },
    performanceScore: 4.8,
    skills: ["إدارة الموارد البشرية", "القيادة", "التخطيط الاستراتيجي"],
    certifications: ["PHR", "SHRM-CP"],
    directReports: ["2", "3", "4"],
    workLocation: "مكتب",
    contractType: "دوام كامل",
    lastLoginDate: "2024-02-10T08:30:00Z",
    createdAt: "2020-01-15T00:00:00Z",
    updatedAt: "2024-02-10T08:30:00Z",
  },
  {
    id: "2",
    name: "نورا عبدالله العتيبي",
    email: "nora.alotaibi@company.com",
    phone: "+966502345678",
    position: "أخصائية موارد بشرية",
    department: "الموارد البشرية",
    salary: 12000,
    joinDate: "2021-06-01",
    status: "نشط",
    avatar: "/diverse-female-avatar.png",
    nationalId: "2345678901",
    birthDate: "1990-07-15",
    address: "جدة، المملكة العربية السعودية",
    emergencyContact: {
      name: "عبدالله العتيبي",
      phone: "+966502345679",
      relationship: "والد",
    },
    bankAccount: {
      iban: "SA2345678901234567890123",
      bankName: "بنك الراجحي",
    },
    performanceScore: 4.5,
    skills: ["التوظيف", "تطوير الموظفين", "إدارة الأداء"],
    certifications: ["CIPD"],
    manager: "1",
    directReports: [],
    workLocation: "مكتب",
    contractType: "دوام كامل",
    lastLoginDate: "2024-02-09T14:20:00Z",
    createdAt: "2021-06-01T00:00:00Z",
    updatedAt: "2024-02-09T14:20:00Z",
  },
  {
    id: "3",
    name: "خالد أحمد الغامدي",
    email: "khalid.alghamdi@company.com",
    phone: "+966503456789",
    position: "مطور برمجيات أول",
    department: "تقنية المعلومات",
    salary: 15000,
    joinDate: "2019-03-10",
    status: "نشط",
    avatar: "/male-avatar.png",
    nationalId: "3456789012",
    birthDate: "1988-11-25",
    address: "الدمام، المملكة العربية السعودية",
    emergencyContact: {
      name: "سارة الغامدي",
      phone: "+966503456790",
      relationship: "زوجة",
    },
    bankAccount: {
      iban: "SA3456789012345678901234",
      bankName: "بنك سامبا",
    },
    performanceScore: 4.7,
    skills: ["React", "Node.js", "Python", "AWS"],
    certifications: ["AWS Solutions Architect", "React Developer"],
    manager: "1",
    directReports: ["5", "6"],
    workLocation: "مختلط",
    contractType: "دوام كامل",
    lastLoginDate: "2024-02-10T09:15:00Z",
    createdAt: "2019-03-10T00:00:00Z",
    updatedAt: "2024-02-10T09:15:00Z",
  },
  {
    id: "4",
    name: "مريم سالم القحطاني",
    email: "mariam.alqahtani@company.com",
    phone: "+966504567890",
    position: "محاسبة أولى",
    department: "المالية",
    salary: 13000,
    joinDate: "2020-09-15",
    status: "نشط",
    avatar: "/diverse-female-avatar.png",
    nationalId: "4567890123",
    birthDate: "1987-05-10",
    address: "الرياض، المملكة العربية السعودية",
    emergencyContact: {
      name: "سالم القحطاني",
      phone: "+966504567891",
      relationship: "والد",
    },
    bankAccount: {
      iban: "SA4567890123456789012345",
      bankName: "البنك السعودي للاستثمار",
    },
    performanceScore: 4.3,
    skills: ["المحاسبة المالية", "تحليل البيانات", "Excel المتقدم"],
    certifications: ["CPA", "CMA"],
    manager: "1",
    directReports: [],
    workLocation: "مكتب",
    contractType: "دوام كامل",
    lastLoginDate: "2024-02-09T16:45:00Z",
    createdAt: "2020-09-15T00:00:00Z",
    updatedAt: "2024-02-09T16:45:00Z",
  },
  {
    id: "5",
    name: "عبدالرحمن محمد الشهري",
    email: "abdulrahman.alshehri@company.com",
    phone: "+966505678901",
    position: "مطور واجهات أمامية",
    department: "تقنية المعلومات",
    salary: 11000,
    joinDate: "2022-01-20",
    status: "نشط",
    avatar: "/male-avatar.png",
    nationalId: "5678901234",
    birthDate: "1992-08-30",
    address: "أبها، المملكة العربية السعودية",
    emergencyContact: {
      name: "محمد الشهري",
      phone: "+966505678902",
      relationship: "والد",
    },
    bankAccount: {
      iban: "SA5678901234567890123456",
      bankName: "بنك الرياض",
    },
    performanceScore: 4.2,
    skills: ["React", "TypeScript", "CSS", "UI/UX"],
    certifications: ["React Developer"],
    manager: "3",
    directReports: [],
    workLocation: "عن بعد",
    contractType: "دوام كامل",
    probationEndDate: "2022-07-20",
    lastLoginDate: "2024-02-10T10:30:00Z",
    createdAt: "2022-01-20T00:00:00Z",
    updatedAt: "2024-02-10T10:30:00Z",
  },
  {
    id: "6",
    name: "هند عبدالعزيز النعيمي",
    email: "hind.alnaimi@company.com",
    phone: "+966506789012",
    position: "مصممة جرافيك",
    department: "التسويق",
    salary: 9000,
    joinDate: "2021-11-01",
    status: "في إجازة",
    avatar: "/diverse-female-avatar.png",
    nationalId: "6789012345",
    birthDate: "1993-12-05",
    address: "جدة، المملكة العربية السعودية",
    emergencyContact: {
      name: "عبدالعزيز النعيمي",
      phone: "+966506789013",
      relationship: "والد",
    },
    bankAccount: {
      iban: "SA6789012345678901234567",
      bankName: "البنك الأهلي السعودي",
    },
    performanceScore: 4.0,
    skills: ["Adobe Creative Suite", "UI Design", "Branding"],
    certifications: ["Adobe Certified Expert"],
    manager: "3",
    directReports: [],
    workLocation: "مختلط",
    contractType: "دوام كامل",
    lastLoginDate: "2024-01-25T13:20:00Z",
    createdAt: "2021-11-01T00:00:00Z",
    updatedAt: "2024-01-25T13:20:00Z",
  },
]

// Mock Leave Requests Data
export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: "1",
    employeeId: "2",
    employeeName: "نورا عبدالله العتيبي",
    type: "سنوية",
    startDate: "2024-03-01",
    endDate: "2024-03-05",
    days: 5,
    reason: "إجازة عائلية للسفر",
    status: "في الانتظار",
    submittedDate: "2024-02-10",
    emergencyContact: "+966502345679",
    replacementEmployee: "4",
    handoverNotes: "تسليم المهام للزميلة مريم",
    createdAt: "2024-02-10T09:00:00Z",
    updatedAt: "2024-02-10T09:00:00Z",
  },
  {
    id: "2",
    employeeId: "3",
    employeeName: "خالد أحمد الغامدي",
    type: "مرضية",
    startDate: "2024-02-15",
    endDate: "2024-02-17",
    days: 3,
    reason: "إجراء عملية جراحية بسيطة",
    status: "معتمد",
    submittedDate: "2024-02-08",
    approvedBy: "1",
    approvedDate: "2024-02-09",
    documents: ["medical-certificate.pdf"],
    createdAt: "2024-02-08T14:30:00Z",
    updatedAt: "2024-02-09T10:15:00Z",
  },
  {
    id: "3",
    employeeId: "5",
    employeeName: "عبدالرحمن محمد الشهري",
    type: "طارئة",
    startDate: "2024-02-12",
    endDate: "2024-02-12",
    days: 1,
    reason: "ظروف عائلية طارئة",
    status: "معتمد",
    submittedDate: "2024-02-11",
    approvedBy: "3",
    approvedDate: "2024-02-11",
    emergencyContact: "+966505678902",
    createdAt: "2024-02-11T20:45:00Z",
    updatedAt: "2024-02-11T21:00:00Z",
  },
  {
    id: "4",
    employeeId: "6",
    employeeName: "هند عبدالعزيز النعيمي",
    type: "أمومة",
    startDate: "2024-01-15",
    endDate: "2024-04-15",
    days: 90,
    reason: "إجازة أمومة",
    status: "معتمد",
    submittedDate: "2024-01-01",
    approvedBy: "1",
    approvedDate: "2024-01-02",
    documents: ["birth-certificate.pdf", "medical-report.pdf"],
    createdAt: "2024-01-01T10:00:00Z",
    updatedAt: "2024-01-02T08:30:00Z",
  },
  {
    id: "5",
    employeeId: "4",
    employeeName: "مريم سالم القحطاني",
    type: "سنوية",
    startDate: "2024-04-01",
    endDate: "2024-04-10",
    days: 10,
    reason: "إجازة سنوية للراحة",
    status: "في الانتظار",
    submittedDate: "2024-02-09",
    replacementEmployee: "2",
    handoverNotes: "تسليم التقارير المالية الشهرية",
    createdAt: "2024-02-09T11:20:00Z",
    updatedAt: "2024-02-09T11:20:00Z",
  },
]

// Mock Courses Data
export const mockCourses: Course[] = [
  {
    id: "1",
    title: "أساسيات الذكاء الاصطناعي",
    description: "دورة تدريبية شاملة حول أساسيات الذكاء الاصطناعي وتطبيقاته في بيئة العمل",
    instructor: "د. محمد العلي",
    duration: 40,
    startDate: "2024-03-01",
    endDate: "2024-03-15",
    maxStudents: 25,
    enrolled: 18,
    category: "تقني",
    level: "متوسط",
    format: "مختلط",
    location: "قاعة التدريب الرئيسية",
    meetingLink: "https://zoom.us/j/123456789",
    materials: ["كتاب الذكاء الاصطناعي", "عروض تقديمية", "تمارين عملية"],
    prerequisites: ["أساسيات البرمجة", "الرياضيات الأساسية"],
    objectives: ["فهم مفاهيم الذكاء الاصطناعي الأساسية", "تطبيق خوارزميات التعلم الآلي", "تطوير نماذج ذكية بسيطة"],
    assessment: {
      type: "مشروع",
      passingScore: 70,
    },
    certificate: true,
    cost: 2500,
    provider: "معهد التقنية المتقدمة",
    rating: 4.8,
    reviews: [
      {
        id: "1",
        employeeId: "3",
        employeeName: "خالد أحمد الغامدي",
        rating: 5,
        comment: "دورة ممتازة ومفيدة جداً",
        date: "2024-01-20",
      },
    ],
    status: "مجدول",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-02-10T00:00:00Z",
  },
  {
    id: "2",
    title: "مهارات القيادة الفعالة",
    description: "تطوير مهارات القيادة والإدارة للمديرين والمشرفين",
    instructor: "أ. سارة الأحمد",
    duration: 24,
    startDate: "2024-02-15",
    endDate: "2024-02-22",
    maxStudents: 20,
    enrolled: 15,
    category: "قيادي",
    level: "متقدم",
    format: "حضوري",
    location: "قاعة المؤتمرات",
    materials: ["دليل القيادة", "حالات دراسية", "تمارين جماعية"],
    prerequisites: ["خبرة إدارية لا تقل عن سنتين"],
    objectives: ["تطوير مهارات القيادة الشخصية", "إدارة الفرق بفعالية", "اتخاذ القرارات الاستراتيجية"],
    assessment: {
      type: "تقييم عملي",
      passingScore: 75,
    },
    certificate: true,
    cost: 3000,
    provider: "أكاديمية القيادة",
    rating: 4.9,
    reviews: [],
    status: "قيد التنفيذ",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "3",
    title: "الأمن السيبراني للمؤسسات",
    description: "حماية البيانات والأنظمة من التهديدات السيبرانية",
    instructor: "م. أحمد الزهراني",
    duration: 32,
    startDate: "2024-03-10",
    endDate: "2024-03-24",
    maxStudents: 30,
    enrolled: 22,
    category: "تقني",
    level: "متوسط",
    format: "عن بعد",
    meetingLink: "https://teams.microsoft.com/l/meetup-join/...",
    materials: ["دليل الأمن السيبراني", "أدوات الحماية", "سيناريوهات الاختراق"],
    prerequisites: ["أساسيات الشبكات", "أساسيات أنظمة التشغيل"],
    objectives: ["تحديد التهديدات السيبرانية", "تطبيق إجراءات الحماية", "إدارة الحوادث الأمنية"],
    assessment: {
      type: "امتحان",
      passingScore: 80,
    },
    certificate: true,
    cost: 2800,
    provider: "مركز الأمن السيبراني",
    rating: 4.7,
    reviews: [],
    status: "مجدول",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-05T00:00:00Z",
  },
  {
    id: "4",
    title: "إدارة المشاريع الاحترافية",
    description: "منهجيات إدارة المشاريع وأفضل الممارسات",
    instructor: "د. فاطمة الخالد",
    duration: 48,
    startDate: "2024-04-01",
    endDate: "2024-04-20",
    maxStudents: 25,
    enrolled: 12,
    category: "إداري",
    level: "متقدم",
    format: "مختلط",
    location: "مركز التدريب المتقدم",
    meetingLink: "https://zoom.us/j/987654321",
    materials: ["دليل PMP", "برامج إدارة المشاريع", "قوالب المشاريع"],
    prerequisites: ["خبرة في إدارة المشاريع", "أساسيات الإدارة"],
    objectives: ["إتقان منهجيات إدارة المشاريع", "استخدام أدوات التخطيط والمتابعة", "إدارة المخاطر والجودة"],
    assessment: {
      type: "مشروع",
      passingScore: 75,
    },
    certificate: true,
    cost: 4000,
    provider: "معهد إدارة المشاريع",
    rating: 4.6,
    reviews: [],
    status: "مجدول",
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "5",
    title: "التسويق الرقمي المتقدم",
    description: "استراتيجيات التسويق الرقمي ووسائل التواصل الاجتماعي",
    instructor: "أ. عبدالله المطيري",
    duration: 36,
    startDate: "2024-03-20",
    endDate: "2024-04-05",
    maxStudents: 20,
    enrolled: 16,
    category: "تقني",
    level: "متوسط",
    format: "عن بعد",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    materials: ["دليل التسويق الرقمي", "أدوات التحليل", "حملات إعلانية"],
    prerequisites: ["أساسيات التسويق", "استخدام الإنترنت"],
    objectives: ["تطوير استراتيجيات التسويق الرقمي", "إدارة حملات الإعلانات الرقمية", "تحليل البيانات التسويقية"],
    assessment: {
      type: "مشروع",
      passingScore: 70,
    },
    certificate: true,
    cost: 2200,
    provider: "أكاديمية التسويق الرقمي",
    rating: 4.5,
    reviews: [],
    status: "مجدول",
    createdAt: "2024-02-20T00:00:00Z",
    updatedAt: "2024-02-20T00:00:00Z",
  },
]

// Mock Notifications Data
export const mockNotifications: Notification[] = [
  {
    id: "1",
    userId: "1",
    title: "طلب إجازة جديد",
    message: "تم تقديم طلب إجازة جديد من نورا العتيبي",
    type: "معلومات",
    priority: "عادي",
    read: false,
    actionUrl: "/leave-requests/1",
    actionText: "مراجعة الطلب",
    metadata: {
      requestId: "1",
      employeeId: "2",
    },
    createdAt: "2024-02-10T09:00:00Z",
  },
  {
    id: "2",
    userId: "2",
    title: "تم اعتماد طلب الإجازة",
    message: "تم اعتماد طلب الإجازة المرضية الخاص بك",
    type: "نجاح",
    priority: "عالي",
    read: true,
    actionUrl: "/my-leaves",
    actionText: "عرض التفاصيل",
    metadata: {
      requestId: "2",
    },
    createdAt: "2024-02-09T10:15:00Z",
    readAt: "2024-02-09T14:30:00Z",
  },
  {
    id: "3",
    userId: "3",
    title: "دورة تدريبية جديدة",
    message: "تم إضافة دورة الأمن السيبراني - سجل الآن",
    type: "معلومات",
    priority: "عادي",
    read: false,
    actionUrl: "/courses/3",
    actionText: "التسجيل",
    metadata: {
      courseId: "3",
    },
    createdAt: "2024-02-08T16:20:00Z",
  },
  {
    id: "4",
    userId: "4",
    title: "تذكير: تقييم الأداء",
    message: "موعد تقييم الأداء السنوي خلال أسبوع",
    type: "تذكير",
    priority: "عالي",
    read: false,
    actionUrl: "/performance/review",
    actionText: "بدء التقييم",
    expiresAt: "2024-02-20T00:00:00Z",
    createdAt: "2024-02-07T08:00:00Z",
  },
  {
    id: "5",
    userId: "5",
    title: "انتهاء فترة التجربة",
    message: "تهانينا! تم تثبيتك في المنصب بنجاح",
    type: "نجاح",
    priority: "عالي",
    read: true,
    metadata: {
      probationEndDate: "2022-07-20",
    },
    createdAt: "2022-07-20T09:00:00Z",
    readAt: "2022-07-20T10:15:00Z",
  },
]

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalEmployees: 247,
  activeEmployees: 198,
  pendingLeaves: 12,
  completedTrainings: 156,
  averagePerformance: 4.3,
  monthlyGrowth: 5.2,
  departmentStats: [
    {
      name: "تقنية المعلومات",
      employeeCount: 45,
      averagePerformance: 4.5,
      pendingLeaves: 3,
      completedTrainings: 38,
    },
    {
      name: "الموارد البشرية",
      employeeCount: 12,
      averagePerformance: 4.7,
      pendingLeaves: 1,
      completedTrainings: 15,
    },
    {
      name: "المالية",
      employeeCount: 18,
      averagePerformance: 4.2,
      pendingLeaves: 2,
      completedTrainings: 22,
    },
    {
      name: "التسويق",
      employeeCount: 25,
      averagePerformance: 4.1,
      pendingLeaves: 4,
      completedTrainings: 28,
    },
    {
      name: "المبيعات",
      employeeCount: 35,
      averagePerformance: 4.0,
      pendingLeaves: 2,
      completedTrainings: 31,
    },
  ],
  recentActivities: [
    {
      id: "1",
      type: "employee",
      title: "موظف جديد",
      description: "تم إضافة موظف جديد إلى قسم التقنية",
      timestamp: "2024-02-10T10:30:00Z",
      userId: "1",
      userName: "أحمد السعد",
      metadata: {
        employeeId: "7",
        department: "تقنية المعلومات",
      },
    },
    {
      id: "2",
      type: "leave",
      title: "طلب إجازة",
      description: "طلب إجازة جديد في انتظار الموافقة",
      timestamp: "2024-02-10T09:00:00Z",
      userId: "2",
      userName: "نورا العتيبي",
      metadata: {
        requestId: "1",
        type: "سنوية",
      },
    },
    {
      id: "3",
      type: "training",
      title: "دورة تدريبية",
      description: "اكتملت دورة مهارات القيادة بنجاح",
      timestamp: "2024-02-09T16:00:00Z",
      userId: "1",
      userName: "أحمد السعد",
      metadata: {
        courseId: "2",
        participants: 15,
      },
    },
    {
      id: "4",
      type: "performance",
      title: "تقييم أداء",
      description: "تم إكمال تقييم الأداء الربع سنوي",
      timestamp: "2024-02-08T14:20:00Z",
      userId: "3",
      userName: "خالد الغامدي",
      metadata: {
        reviewId: "1",
        score: 4.5,
      },
    },
  ],
}

// Mock Payroll Records
export const mockPayrollRecords: PayrollRecord[] = [
  {
    id: "1",
    employeeId: "1",
    period: { month: 1, year: 2024 },
    basicSalary: 18000,
    allowances: {
      housing: 5400,
      transportation: 1000,
      food: 500,
      mobile: 200,
      other: 0,
    },
    overtime: {
      hours: 0,
      rate: 0,
      amount: 0,
    },
    bonuses: {
      performance: 2000,
      annual: 0,
      other: 0,
    },
    deductions: {
      socialInsurance: 1800,
      tax: 0,
      loan: 0,
      advance: 0,
      other: 0,
    },
    netSalary: 25300,
    paymentDate: "2024-01-31",
    paymentMethod: "تحويل بنكي",
    status: "مدفوع",
    approvedBy: "1",
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-01-31T00:00:00Z",
  },
  {
    id: "2",
    employeeId: "2",
    period: { month: 1, year: 2024 },
    basicSalary: 12000,
    allowances: {
      housing: 3600,
      transportation: 800,
      food: 400,
      mobile: 150,
      other: 0,
    },
    overtime: {
      hours: 5,
      rate: 75,
      amount: 375,
    },
    bonuses: {
      performance: 1000,
      annual: 0,
      other: 0,
    },
    deductions: {
      socialInsurance: 1200,
      tax: 0,
      loan: 500,
      advance: 0,
      other: 0,
    },
    netSalary: 16625,
    paymentDate: "2024-01-31",
    paymentMethod: "تحويل بنكي",
    status: "مدفوع",
    approvedBy: "1",
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-01-31T00:00:00Z",
  },
]

// Mock Attendance Records
export const mockAttendanceRecords: AttendanceEntry[] = [
  {
    id: "1",
    employeeId: "1",
    date: "2024-02-10",
    checkIn: "08:00",
    checkOut: "17:00",
    breakStart: "12:00",
    breakEnd: "13:00",
    totalHours: 8,
    regularHours: 8,
    overtimeHours: 0,
    status: "حاضر",
    location: "مكتب",
    createdAt: "2024-02-10T08:00:00Z",
    updatedAt: "2024-02-10T17:00:00Z",
  },
  {
    id: "2",
    employeeId: "2",
    date: "2024-02-10",
    checkIn: "08:15",
    checkOut: "17:30",
    breakStart: "12:30",
    breakEnd: "13:30",
    totalHours: 8.25,
    regularHours: 8,
    overtimeHours: 0.25,
    status: "متأخر",
    location: "مكتب",
    notes: "تأخير بسبب الازدحام المروري",
    createdAt: "2024-02-10T08:15:00Z",
    updatedAt: "2024-02-10T17:30:00Z",
  },
  {
    id: "3",
    employeeId: "5",
    date: "2024-02-10",
    checkIn: "09:00",
    checkOut: "18:00",
    totalHours: 8,
    regularHours: 8,
    overtimeHours: 0,
    status: "حاضر",
    location: "عن بعد",
    createdAt: "2024-02-10T09:00:00Z",
    updatedAt: "2024-02-10T18:00:00Z",
  },
]

// Mock Documents
export const mockDocuments: Document[] = [
  {
    id: "1",
    title: "سياسة الموارد البشرية 2024",
    description: "السياسات والإجراءات المحدثة للموارد البشرية",
    type: "سياسة",
    category: "موارد بشرية",
    fileName: "hr-policy-2024.pdf",
    fileSize: 2048576,
    mimeType: "application/pdf",
    url: "/documents/hr-policy-2024.pdf",
    uploadedBy: "1",
    tags: ["سياسة", "موارد بشرية", "2024"],
    version: "1.0",
    status: "معتمد",
    accessLevel: "عام",
    relatedEmployees: [],
    approvedBy: "1",
    approvedDate: "2024-01-01",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "نموذج طلب إجازة",
    description: "النموذج الرسمي لطلب الإجازات",
    type: "نموذج",
    category: "موارد بشرية",
    fileName: "leave-request-form.pdf",
    fileSize: 512000,
    mimeType: "application/pdf",
    url: "/documents/leave-request-form.pdf",
    uploadedBy: "2",
    tags: ["نموذج", "إجازة"],
    version: "2.1",
    status: "معتمد",
    accessLevel: "عام",
    relatedEmployees: [],
    approvedBy: "1",
    approvedDate: "2024-01-15",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
]

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: "1",
    name: "تطوير نظام الموارد البشرية",
    description: "تطوير نظام شامل لإدارة الموارد البشرية",
    status: "قيد التنفيذ",
    priority: "عالي",
    startDate: "2024-01-01",
    endDate: "2024-06-30",
    budget: 500000,
    actualCost: 250000,
    progress: 60,
    manager: "3",
    team: ["3", "5", "6"],
    department: "تقنية المعلومات",
    milestones: [
      {
        id: "1",
        title: "تحليل المتطلبات",
        description: "جمع وتحليل متطلبات النظام",
        dueDate: "2024-02-01",
        status: "مكتمل",
        completionDate: "2024-01-28",
      },
      {
        id: "2",
        title: "التصميم والتطوير",
        description: "تصميم وتطوير النظام",
        dueDate: "2024-05-01",
        status: "قيد التنفيذ",
      },
    ],
    tasks: [
      {
        id: "1",
        title: "تصميم قاعدة البيانات",
        description: "تصميم هيكل قاعدة البيانات",
        assignedTo: "3",
        status: "مكتمل",
        priority: "عالي",
        estimatedHours: 40,
        actualHours: 35,
        startDate: "2024-01-15",
        dueDate: "2024-01-25",
        completionDate: "2024-01-24",
        dependencies: [],
        tags: ["قاعدة بيانات", "تصميم"],
      },
    ],
    risks: [
      {
        id: "1",
        title: "تأخير في التسليم",
        description: "احتمالية تأخير في تسليم المشروع",
        probability: "متوسط",
        impact: "عالي",
        status: "قيد المراقبة",
        mitigation: "زيادة عدد المطورين",
        owner: "3",
      },
    ],
    documents: ["1"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-02-10T00:00:00Z",
  },
]

// Mock Job Postings
export const mockJobPostings: JobPosting[] = [
  {
    id: "1",
    title: "مطور برمجيات أول",
    department: "تقنية المعلومات",
    location: "الرياض",
    type: "دوام كامل",
    level: "كبير",
    description: "نبحث عن مطور برمجيات خبير للانضمام إلى فريقنا",
    requirements: ["خبرة لا تقل عن 5 سنوات في تطوير البرمجيات", "إتقان React و Node.js", "خبرة في قواعد البيانات"],
    responsibilities: ["تطوير وصيانة التطبيقات", "مراجعة الكود", "توجيه المطورين المبتدئين"],
    qualifications: ["بكالوريوس في علوم الحاسب أو ما يعادلها", "شهادات تقنية معتمدة"],
    skills: ["React", "Node.js", "JavaScript", "SQL"],
    salaryRange: { min: 12000, max: 18000 },
    benefits: ["تأمين صحي", "إجازة سنوية", "تدريب مستمر"],
    applicationDeadline: "2024-03-15",
    status: "منشور",
    postedBy: "1",
    applicationsCount: 25,
    viewsCount: 150,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
]

// Export all mock data
